/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCustomer: typeof import('./src/components/addCustomer.vue')['default']
    AddSalesOrder: typeof import('./src/components/addSalesOrder.vue')['default']
    CaptureLocation: typeof import('./src/components/captureLocation.vue')['default']
    CheckIn: typeof import('./src/components/CheckIn.vue')['default']
    CustomerList: typeof import('./src/components/customerList.vue')['default']
    InstallPrompt: typeof import('./src/components/InstallPrompt.vue')['default']
    KpiCard: typeof import('./src/components/KpiCard.vue')['default']
    OrderDetails: typeof import('./src/components/OrderDetails.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    Profile: typeof import('./src/components/profile.vue')['default']
    QuickLinks: typeof import('./src/components/QuickLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgBarChart: typeof import('./src/components/SvgBarChart.vue')['default']
    SvgLineChart: typeof import('./src/components/SvgLineChart.vue')['default']
    SyncBanner: typeof import('./src/components/SyncBanner.vue')['default']
    Tabs: typeof import('./src/components/tabs.vue')['default']
    UserStatus: typeof import('./src/components/userStatus.vue')['default']
  }
}
